version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - run: rm -fr ./vendor
    - run: golint -set_exit_status ./...
    - run: go mod vendor
    - run: go test -v ./...
